server:
   port: 8888
spring:
  profiles:
    active: native
  cloud:
     config:
       server:
           native:
              searchLocations: classpath:config/,classpath:config/licenseservice
              #File System
              #searchLocations: file:///home/docker/Documents/config/licenseservice